### PR TITLE
Update qgis base image, close #50

### LINKED ISSUE #50: Use suggests image as basis for qgis image
See https://github.com/geocompx/geocompr/issues/1108 and failing workflows

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by jannes-m** [comment]
I think this would only work if the suggests image installs the stuff also installed by the geospatial image, specifically I refer to https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_geospatial.sh. However, wouldn't it be easier to just install the missing R libraries **bslib** and **downlilt** for the qgis image?

**Comment by Robinlovelace** [comment]
> However, wouldn't it be easier to just install the missing R libraries **bslib** and **downlilt** for the qgis image?

The thing is that those package are installed in the package, or at least they should be, because the image includes the installation step. So I guess  there's something about this bleeding edge image that prevents them being installed: https://hub.docker.com/r/rocker/geospatial/tags

**Comment by Robinlovelace** [comment]
See here: https://github.com/geocompx/docker/blob/f8aac8a7476e60e262d5444470d9f00ed694ce3e/qgis/Dockerfile#L73

**Comment by Robinlovelace** [comment]
But yeah, happy NOT to merge this. Maybe we just need to re-run after the new images have been built.

**Comment by Robinlovelace** [comment]
Just testing it with 

```
docker run -it rocker/geospatial:dev-osgeo /bin/bash
```

**Comment by Robinlovelace** [comment]
Closing as the motivating issue is now fixed I think: https://github.com/geocompx/geocompr/commit/7981e0dacfc966009b32cffa08996e4ea61ebc16

**Pull request closed without merging**
